---
apiVersion: v1
kind: Service
metadata:
  name: vert-fileexplorer-prd-front
  namespace: vert-fileexplorer-prd
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: vert-fileexplorer-prd-front
