---
apiVersion: v1
kind: Service
metadata:
  name: <%= namespace %>-front
  namespace: <%= namespace %>
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: <%= namespace %>-front
